con <- url("http://biostat.jhsph.edu/~jleek/contact.html")
htmlcode <- readLines(con)
close(con)
a<-nchar(html[10])
b<-nchar(html[20])
c<-nchar(html[30])
d<-nchar(html[100])
print(a)
print(b)
print(c)
print(d)
